# Generated by Django 5.1.1 on 2024-09-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holidays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holidaytype',
            name='img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
